### ISSUE TITLE
수박게임 공용 TODO(2)

### ISSUE THREAD

**Issue by itsdangerous** [INU-Fake-Developers/watermelon_game_test_seunggyu#2]
- [ ]  수박게임 제작의도(덕질, 기념일, 친목도모 등) 선정
- [ ] 이미지 고르기
- [ ] 고른 이미지 편집하기 - 포도
- [ ] 고른 이미지 편집하기 - 앵두
- [ ] 고른 이미지 편집하기 - 귤
- [ ] 고른 이미지 편집하기 - 레몬
- [ ] 고른 이미지 편집하기 - 키위
- [ ] 고른 이미지 편집하기 - 토마토
- [ ] 고른 이미지 편집하기 - 복숭아
- [ ] 고른 이미지 편집하기 - 파인애플
- [ ] 고른 이미지 편집하기 - 야자
- [ ] 고른 이미지 편집하기 - 수박
- [ ] 고른 이미지 편집하기 - 큰 수박
