### ISSUE TITLE
수박게임 공용 TODO(3)

### ISSUE THREAD

**Issue by itsdangerous** [INU-Fake-Developers/watermelon_game_test_seunggyu#3]
- [ ] 고른 이미지 편집하기
- [ ] 편집한 이미지 변환 후 프로젝트 폴더에 추가하기
- [ ] 로컬 환경에서 테스트하기
